virtuoso:
  build: ./docker/virtuoso/
  restart: always
  ports:
    - 8890:8890
    - 1111:1111
  environment:
    PWDDBA: "izesek1Taizoo!boo"
  volumes:
    - ./data/virtuoso/:/var/lib/virtuoso/db/

ontowiki:
  build: ./docker/ontowiki/
  restart: always
  links:
    - virtuoso
  ports:
    - 80:80
  volumes:
    - ./config/ontowiki/:/config/

