virtuoso:
  build: ./docker/virtuoso/
  restart: always
  expose:
    - 8890
    - 1111
  environment:
    PWDDBA: "izesek1Taizoo!boo"
  volumes:
    - ./data/virtuoso/:/var/lib/virtuoso/db/

ontowiki:
  build: ./docker/ontowiki/
  restart: always
  links:
    - virtuoso
  ports:
    - 8580:80
  volumes:
    - ./config/ontowiki/:/config/

